#pragma once

#include <base/types.h>

#include <optional>

namespace DB {

/** Execution options for GQL queries.
 *
 * This is the GQL counterpart of SelectQueryOptions. It intentionally does NOT
 * inherit from SelectQueryOptions because GQL is not a SELECT and many SELECT-
 * specific flags (subquery_depth, is_create_view, to_stage, etc.) do not apply.
 *
 * The InterpreterFactory create_fn maps the small subset of execution-level
 * flags that are meaningful for GQL from SelectQueryOptions to this structure.
 */
struct GQLQueryOptions {
  /// The interpreter was created only for query analysis (e.g. getSampleBlock).
  bool only_analyze = false;

  /// Skip quota enforcement. Used for internal/generated queries.
  bool ignore_quota = false;

  /// Skip limit enforcement. Used for internal/generated queries.
  bool ignore_limits = false;

  /// Skip header-changing optimization passes. Used when executing on shards
  /// or inside CREATE VIEW, where only name/type resolution is safe.
  bool ignore_ast_optimizations = false;

  /// The query is internal (generated by the system, not the user).
  bool is_internal = false;

  /// The query is an EXPLAIN query.
  bool is_explain = false;

  /// Shard information for distributed query execution.
  std::optional<UInt32> shard_num;
  std::optional<UInt32> shard_count;

  GQLQueryOptions() = default;

  GQLQueryOptions& analyze(bool dry_run = true) {
    only_analyze = dry_run;
    return *this;
  }

  GQLQueryOptions& ignoreLimits(bool value = true) {
    ignore_limits = value;
    return *this;
  }

  GQLQueryOptions& ignoreQuota(bool value = true) {
    ignore_quota = value;
    return *this;
  }

  GQLQueryOptions& ignoreASTOptimizations(bool value = true) {
    ignore_ast_optimizations = value;
    return *this;
  }

  GQLQueryOptions& setInternal(bool value = true) {
    is_internal = value;
    return *this;
  }

  GQLQueryOptions& setExplain(bool value = true) {
    is_explain = value;
    return *this;
  }

  GQLQueryOptions& setShardInfo(UInt32 shard_num_, UInt32 shard_count_) {
    shard_num = shard_num_;
    shard_count = shard_count_;
    return *this;
  }
};

}  // namespace DB
